### ISSUE TITLE
如何获得top10_match.dict

### ISSUE THREAD

**Issue by Longmeix** [chensyCN/llm4ea_official#1]
作者您好，我想请问下每个数据集中的`top10_match.dict`文件该如何获得，似乎提前产生的，可以上传这部分代码吗~
`infer.py`的第106-107行加载了该文件：
`topk_match_path = os.path.join(dataset_path, f"top{args.topk_match}_match.dict") `

**Comment by chensyCN** [comment]
Hi, I have uploaded the script for the string similarity-based top-k counterpart filter. You can find it here: [str_match_mrr.py](https://github.com/chensyCN/llm4ea_official/blob/master/str_match_mrr.py).

**Comment by chensyCN** [comment]
> 作者您好，我想请问下每个数据集中的`top10_match.dict`文件该如何获得，似乎提前产生的，可以上传这部分代码吗~ `infer.py`的第106-107行加载了该文件： `topk_match_path = os.path.join(dataset_path, f"top{args.topk_match}_match.dict") `

Hi, I have uploaded the script for the string similarity-based top-k counterpart filter. You can find it here: [str_match_mrr.py](https://github.com/chensyCN/llm4ea_official/blob/master/str_match_mrr.py).
